app/views/webpage.py
from flask import request, redirect, url_for, render_template, flash, session
from flask import Blueprint
# from flask_line_api import line

from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import login_user, logout_user, login_required

from app.models.users import User
from app.models.line import MessageHistory
from sqlalchemy import desc
from app import db

webpage = Blueprint('webpage', __name__)

@webpage.route('/')
def display_top_page():
    return render_template('top.html')

@webpage.app_errorhandler(404)
def non_existant_route(error):
    return redirect(url_for('webpage.login'))


# TODO: signUP画面の更新!
@webpage.route('/signup', methods=['GET', 'POST'])
def signup():
    if request.method == 'POST':
        user_id = request.form.get('user_id')
        username = request.form.get('username')
        password = request.form.get('password')
        user = User.query.filter_by(user_id=user_id).first()
        if user:
            flash('Email address already exists!!')
            return redirect(url_for('webpage.signup'))
        new_user = User(user_id=user_id, username=username, password=generate_password_hash(password, method='sha256'))
        db.session.add(new_user)
        db.session.commit()
        flash('正常に登録できました。ログインしてください！')
        return redirect(url_for('webpage.login'))

    else:
        return render_template('signup.html')


@webpage.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        user_id = request.form.get('user_id')
        password = request.form.get('password')
        remember = True if request.form.get('remember') else False 

        user = User.query.filter_by(user_id=user_id).first()

        if not user or not check_password_hash(user.password, password):
            flash('Please check your login details and try again!!')
            return redirect(url_for('webpage.login'))
        
        login_user(user, remember=remember)
        flash('ログインしました！')
        return redirect(url_for('webpage.display_top_page'))
    
    # GETメソッドの場合
    else:
        return render_template('login.html')

@webpage.route('/mail', methods=['GET', 'POST'])
def send_message_to_change_password():
    pass
    # form = AddressForm()
    # if request.method == 'POST' and form.validate_on_submit():
    #     # TODO: 現存するuser_idか確認
    #     token = _create_token(form.userid.data, app.secret_key,  salt='shio')
    #     url = url_for('view.new_pwd', token=token, _external=True)

    #     line.send_url_for_change_password(form.userid.data, url)
    #     flash(f'入力されたLINEユーザーにパスワード変更用URLを送信しました')

    # # ページ表示
    # return render_template('mail.html', form=form)

@webpage.route('/logout')
@login_required
def logout():
    logout_user()
    flash('ログアウトしました')
    return redirect(url_for('webpage.display_top_page'))

# TODO: userinfoができたら削除
# @webpage.route('/userlist')
# @login_required
# def display_user_list():
#     user_list = User.query.all()
#     return render_template('userlist.html', user_list=user_list)

@webpage.route('/info/<string:user_id>') # HACK: 本当はURLにはusernameを表示させたい
@login_required
def display_user_info(user_id):
    user_list = User.query.all()
    message_histories = MessageHistory.query.filter(MessageHistory.user_id == user_id).order_by(desc(MessageHistory.timestamp)).limit(20).all()
    return render_template('userinfo.html', user_list=user_list, message_histories=message_histories)

@webpage.route('/profile')
def display_my_profile():
    return render_template('profile.html')

@webpage.route('/linebot')
def display_linebot_info():
    return render_template('linebot.html')

app/templates/layout.html
<!doctype html>
<html lang="en">

<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
<meta http-equiv="x-ua-compatible" content="ie=edge" />
<title>Portfolio of Ry-Ku</title>
<!-- Font Awesome ETC twitter facebook icon -->
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css" />
<!-- Avant UI -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<link rel="stylesheet" href="{{ url_for('static', filename='avantui.css') }}">
</head>

<div class="container-fluid">
<body>
<header>
  <nav class="navbar navbar-expand-lg navbar-light bg-white">
    <a class="navbar-brand" href="/">
        <span class="text-primary">M</span>y<span class="text-primary">P</span>ortfolio
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar5" aria-controls="navbar5" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbar5">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              {% if not current_user.is_authenticated %}
                  <a class="nav-link active" aria-current="page" href="{{ url_for('webpage.login') }}">Login</a>
              {% else %}
                  <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Logined</a>
              {% endif %}
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('webpage.logout') }}">Logout</a>
            </li>
            {% if not current_user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{{ url_for('webpage.signup') }}">SignUp</a>
                </li>
            {% endif %}
        </ul>
        <ul class="nav mb-3 mb-lg-0">
            <li class="nav-item">
                <a class="nav-link py-0 pl-0 pl-lg-3" href="#"><i class="fab fa-facebook-f"></i></a>
            </li>
            <li class="nav-item">
                <a class="nav-link py-0" href="#"><i class="fab fa-twitter"></i></a>
            </li>
            <li class="nav-item">
                <a class="nav-link py-0" href="#"><i class="fab fa-instagram"></i></a>
            </li>
        </ul>
    </div>
  </nav>
</header>

    {% for message in get_flashed_messages() %}
        <div class="alert alert-info" role="alert">
            {{ message }}
        </div>
    {% endfor %}

    <div class="blog-body">
        {% block body %}{% endblock %}
    </div>
    
<!-- Avant Ui Javascript -->
<script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js" integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o" crossorigin="anonymous"></script>
<script src="{{ url_for('static', filename='avantui.js') }}"></script>
</body>
</div>

app/templates/linebot.html
{% extends "layout.html" %}
{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-4 col-md-12 mb-4 mt-3 mt-lg-0">
            <!-- LINE動画 -->
            <div class="card card-article position-relative mb-4">
                <video controls class="embed-responsive-item" src="static/movies/line_fifteen_howto.mov"></video>
                <span class="card-tag position-absolute small text-white bg-warning rounded m-3 my-2 px-2 py-1">How to Use</span>
                <div class="card-body">
                    <h6 class="card-title">使い方</h6>
                    <p class="card-text">My Portfolioを友達登録後、動画のようにトークルームで質問文を送信してください。</p>
                </div>
            </div>

            <!-- QRコード -->
            <div class="card">
                <div class="row no-gutters">
                    <div class="col-4 my-auto">
                        <img width="150" height="150" src="https://qr-official.line.me/sid/M/927fbtyw.png?shortenUrl=true">
                    </div>
                    <div class="col-8">
                        <div class="card-body">
                            <h5 class="card-title">LINE BOT QR CODE</h5>
                            <p class="card-text">
                                左のQRコードを読み取って友達登録できます。
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-4 col-md-12 mb-4 mt-3 mt-lg-0">
            <div class="card border-success">
                <div class="card-body">
                  <h5 class="card-title">自己紹介メッセージ</h5>
                  <p class="card-text">返信が用意されているメッセージ一覧</p>
                </div>
            </div><!-- /div.class.card -->
            <div class="accordion" id="accordion">
                <div class="accordion-item">
                    <h3 id="accordion-heading-1" class="collapsed d-flex justify-content-between align-items-center" data-toggle="collapse" data-target="#accordion-collapse-1" aria-expanded="true" aria-controls="accordion-collapse-1">
                        github 
                        <span class="accordion-icon">&#10005;</span>
                    </h3>
                    <div id="accordion-collapse-1" class="collapse" aria-labelledby="accordion-heading-1" data-parent="#accordion">
                        <div class="px-3 pb-3">
                          私が個人開発に使用しているgithubリポジトリのURLを返信します。
                        </div>
                    </div>
                </div>
                <div class="accordion-item">
                    <h3 id="accordion-heading-2" class="collapsed d-flex justify-content-between align-items-center" data-toggle="collapse" data-target="#accordion-collapse-2" aria-expanded="true" aria-controls="accordion-collapse-2">
                        年齢 
                        <span class="accordion-icon">&#10005;</span>
                    </h3>
                    <div id="accordion-collapse-2" class="collapse" aria-labelledby="accordion-heading-2" data-parent="#accordion">
                        <div class="px-3 pb-3">
                          メッセージ送信時点での私の年齢を返信します。
                        </div>
                    </div>
                </div>
                <div class="accordion-item">
                    <h3 id="accordion-heading-3" class="collapsed d-flex justify-content-between align-items-center" data-toggle="collapse" data-target="#accordion-collapse-3" aria-expanded="true" aria-controls="accordion-collapse-3">
                        ガクチカ
                        <span class="accordion-icon">&#10005;</span>
                    </h3>
                    <div id="accordion-collapse-3" class="collapse" aria-labelledby="accordion-heading-3" data-parent="#accordion">
                        <div class="px-3 pb-3">
                          私が学生時代に力を入れていたことを返信します。
                        </div>
                    </div>
                </div>
            </div><!-- /div.class.accordion -->
        </div>

        <div class="col">
            <img src="https://qr-official.line.me/sid/M/927fbtyw.png?shortenUrl=true">
            <img src="https://qr-official.line.me/sid/M/927fbtyw.png?shortenUrl=true">
            <img src="https://qr-official.line.me/sid/M/927fbtyw.png?shortenUrl=true">
            <img src="https://qr-official.line.me/sid/M/927fbtyw.png?shortenUrl=true">
            <img src="https://qr-official.line.me/sid/M/927fbtyw.png?shortenUrl=true">
            <img src="https://qr-official.line.me/sid/M/927fbtyw.png?shortenUrl=true">
        </div>
    </div>
</div>
{% endblock %}

app/templates/login.html
{% extends "layout.html" %}
{% block body %}

<div class="container">
        <div class="col-xs-12 col-lg-6 mx-auto">

            <div class="card">
            <article class="card-body">
                <h4 class="card-title text-center mb-4 mt-1">Sign in</h4>
                <hr>
                <p class="text-success text-center">ログイン画面です</p>
                <form action="{{ url_for('webpage.login') }}" method=post>
                <div class="form-group">
                <div class="input-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text"> <i class="fa fa-user"></i> </span>
                    </div>
                    <input name="user_id" class="form-control" placeholder="UserID" type="text">
                </div> <!-- input-group.// -->
                </div> <!-- form-group// -->
                <div class="form-group">
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text"> <i class="fa fa-user"></i> </span>
                        </div>
                        <input name="username" class="form-control" placeholder="Username" type="text">
                    </div> <!-- input-group.// -->
                    </div> <!-- form-group// -->
                <div class="form-group">
                <div class="input-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text"> <i class="fa fa-lock"></i> </span>
                    </div>
                    <input name="password", class="form-control" placeholder="******" type="password">
                </div> <!-- input-group.// -->
                </div> <!-- form-group// -->
                <div class="form-group">
                <button type="submit" class="btn btn-primary btn-block"> Login  </button>
                </div> <!-- form-group// -->
                <p class="text-center"><a href="{{ url_for('webpage.send_message_to_change_password') }}" class="btn">Forgot password?</a></p>
                </form>
            </article>
            </div>

        </div>
</div>

{% endblock %}

app/templates/profile.html
{% extends "layout.html" %}
{% block body %}

<ul class="nav nav-tabs nav-tabs-underline flex-lg-row" id="myTab" role="tablist">
    <li class="nav-item">
        <a class="nav-link active" id="home-tab-underline" data-toggle="tab" href="#home-underline" role="tab" aria-controls="home-underline" aria-selected="true">Profile</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" id="profile-tab-underline" data-toggle="tab" href="#profile-underline" role="tab" aria-controls="profile-underline" aria-selected="false">Science Reserch</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" id="contact-tab-underline" data-toggle="tab" href="#contact-underline" role="tab" aria-controls="contact-underline" aria-selected="false">Portfolio</a>
    </li>
</ul>
<div class="tab-content" id="myTabContent">
    <div class="tab-pane fade show active" id="home-underline" role="tabpanel" aria-labelledby="home-tab-underline">
        <ul class="list-group">
            <li class="list-group-item">Ry-Ku</li>
            <li class="list-group-item">Software Engineer</li>
            <li class="list-group-item">広告運用システム開発。CV率の高いユーザーに広告を配信するためのシステム。各媒体（Google, Twitter）APIの操作や、高CV率ユーザー抽出のための行動ログデータの整形、MLOpsが主な業務内容。</li>
            <li class="list-group-item">
                長所・得意：Python、SQL、データマネジメント、読書（技術書）、新機能・新プロダクト調査、もくもく作業系
            </li>
            <li class="list-group-item">短所・不得意：数学、厳格な会議、早起き</li>
          </ul>
    </div>
    <div class="tab-pane fade" id="profile-underline" role="tabpanel" aria-labelledby="profile-tab-underline">
        <ul class="list-group">
            <li class="list-group-item">千葉大学 基幹工学専攻 電気電子工学コース 修士課程卒</li>
            <li class="list-group-item"><a href="https://www.iee.jp/wp-content/uploads/eiss/conf2018/program/html/class/class4.html" target="_blank">学会発表・電気学会論文誌2018「改良型ブロック構造とフィードバック構造を有するパルスニューラルネットワークによる時系列処理」</a></li>
            <li class="list-group-item">修士論文「スパイキングニューラルネットワークにおける時系列データ学習のための誤差逆伝播法の改良」</li>
          </ul>
    </div>
    <div class="tab-pane fade" id="contact-underline" role="tabpanel" aria-labelledby="contact-tab-underline">
        <li class="list-group-item">This Application!</li>
        <li class="list-group-item"><a href="https://github.com/Ry-Kurihara?tab=repositories" traget="_blank">Github</a></li>
        <li class="list-group-item"><a href="https://selen-ps5.herokuapp.com/" target="_blank">AutoPurchaser</a></li>
    </div>
</div>

{% endblock %}

app/templates/signup.html
{% extends "layout.html" %}
{% block body %}

<div class="container">
        <div class="col-xs-12 col-lg-6 mx-auto">

            <div class="card">
            <article class="card-body">
                <h4 class="card-title text-center mb-4 mt-1">Sign Up</h4>
                <hr>
                <p class="text-success text-center">新規登録画面です</p>
                <form action="{{ url_for('webpage.signup') }}" method=post>
                <div class="form-group">
                <div class="input-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text"> <i class="fa fa-user"></i> </span>
                    </div>
                    <input name="user_id" class="form-control" placeholder="UserID" type="text">
                </div> <!-- input-group.// -->
                </div> <!-- form-group// -->
                <div class="form-group">
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text"> <i class="fa fa-user"></i> </span>
                        </div>
                        <input name="username" class="form-control" placeholder="Username" type="text">
                    </div> <!-- input-group.// -->
                    </div> <!-- form-group// -->
                <div class="form-group">
                <div class="input-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text"> <i class="fa fa-lock"></i> </span>
                    </div>
                    <input name="password", class="form-control" placeholder="******" type="password">
                </div> <!-- input-group.// -->
                </div> <!-- form-group// -->
                <div class="form-group">
                <button type="submit" class="btn btn-primary btn-block"> SignUp  </button>
                </div> <!-- form-group// -->
                </form>
            </article>
            </div>

        </div>
</div>

{% endblock %}

app/templates/top.html
{% extends "layout.html" %}
{% block body %}

<div class="card mb-3" style="max-width: 500px;">
    <div class="row no-gutters">
        <div class="col-md-4">
            <img src="static/images/robot.png" class="card-img rounded-0" alt="image">
        </div>
        <div class="col-md-8">
            <div class="card-body">
                <h5 class="card-title"><a href="{{ url_for('webpage.display_my_profile') }}" class="stretched-link">Profile</a></h5>
                <p class="card-text">
                    Describes my background.
                </p>
            </div>
        </div>
    </div>
</div>

<div class="card mb-3" style="max-width: 500px;">
    <div class="row no-gutters">
        <div class="col-md-4">
            <img src="static/images/robot.png" class="card-img rounded-0" alt="image">
        </div>
        <div class="col-md-8">
            <div class="card-body">
                <h5 class="card-title"><a href="{{ url_for('webpage.display_linebot_info') }}" class="stretched-link">Line Bot</a></h5>
                <p class="card-text">
                    Send my detailed background and etc. in a line message.
                </p>
            </div>
        </div>
    </div>
</div>

<div class="card mb-3" style="max-width: 500px;">
    <div class="row no-gutters">
        <div class="col-md-4">
            <img src="static/images/robot.png" class="card-img rounded-0" alt="image">
        </div>
        <div class="col-md-8">
            <div class="card-body">
                <h5 class="card-title"><a href="{{ url_for('webpage.display_user_info', user_id=current_user.user_id) }}" class="stretched-link">Database</a></h5>
                <p class="card-text">
                    Display a list of messages sent to the bot so far. And etc.
                </p>
                <p class="card-text"><small class="text-muted">login is needed.</small></p>
            </div>
        </div>
    </div>
</div>

{% endblock %}

app/templates/userinfo.html
{% extends "layout.html" %}
{% block body %}

<div class="container-fluid">
    <div class="row">
        <div class="col-xs-12 col-lg-6 mb-4 mt-3 mt-lg-0"><!-- 左カラム -->
            <h2>受信メッセージ履歴（直近20件）</h2>
                <table class="table">
                    <thead class="thead-light">
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">message</th>
                            <th scope="col">timestamp</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for message_history in message_histories %}
                            <tr>
                                <th scope="row">{{ loop.index }}</th>
                                <td>{{ message_history.message }}</td>
                                <td>{{ message_history.timestamp }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
        </div><!-- 左カラム閉じ -->
        <div class="col-xs-12 col-lg-6 mb-4 mt-3 mt-lg-0"><!-- 右カラム -->
            <h2>登録ユーザー（Visible only to admin）</h2>
            <table class="table">
                <thead class="thead-dark">
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">UserID</th>
                        <th scope="col">UserName</th>
                    </tr>
                </thead>
                <tbody>
                    {% for user in user_list %}
                        <tr>
                            <th scope="row">{{ loop.index }}</th>
                            <td>{{ user.user_id }}</td>
                            <td>{{ user.username }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table> 
        </div><!-- 右カラム閉じ -->
    </div>
</div>

{% endblock %}